name: code-quality

on: [push, pull_request]

jobs:

################################ STEP 1: Code Quality Analysis ################################
  code-quality-analysis:
      runs-on: ubuntu-latest
      env:
          RCA_LINK: https://github.com/mozilla/rust-code-analysis/releases/download
          RCA_VERSION: v0.0.25

      steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc jq

      - name: Install rust-code-analysis on Ubuntu
        run: |
          mkdir -p $HOME/.local/bin	
          curl -L "$RCA_LINK/$RCA_VERSION/rust-code-analysis-linux-cli-x86_64.tar.gz" |
          tar xz -C $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run rust-code-analysis
        run: |
          mkdir $HOME/rca-json
          rust-code-analysis-cli --metrics -O json --pr -o "$HOME/rca-json" -p $PWD

      - name: Evaluate code quality
        run: |
          .github/scripts/main.sh

      - name: Prepare Step 1 artifacts
        run: |
          mkdir -p $HOME/final-artifacts/step1
          cp -r $HOME/rca-json/* $HOME/final-artifacts/step1 || echo "No RCA JSON files to copy"
          cp -r $HOME/code-quality-report/* $HOME/final-artifacts/step1 || echo "No code quality report files to copy"

      - name: Upload Step 1 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: ~/final-artifacts/

################################ STEP 2: Code Quality Report ################################
  anomaly-detection:
    runs-on: ubuntu-latest
    needs: code-quality-analysis

    steps:
    - uses: actions/checkout@v4

    - name: Download previous artifacts
      uses: actions/download-artifact@v4
      with:
        name: analysis-results
        path: ~/final-artifacts/

    - name: Simulated anomaly detection step
      run: |
        echo "Starting anomaly detection analysis..."
        echo "Analysing patterns and detecting potential anomalies..."
        echo "Anomaly detection completed successfully."

        mkdir -p $HOME/final-artifacts/step2
        echo "Anomaly Detection Report" > $HOME/final-artifacts/step2/anomaly-detection-report.txt

    - name: Upload updated artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: ~/final-artifacts/
